import type { Metadata } from 'next'

import { ReactNode } from 'react'

import ClientProvider from '@/components/ClientProvider/ClientProvider'
import { Header } from '@/components/Header'

import './../styles/index.scss'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang={'en'}>
      <ClientProvider>
        <body>
          <Header />
          {children}
        </body>
      </ClientProvider>
    </html>
  )
}
